### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zhenglaizhang** [zhenglaizhang/ml-quest#1]
## ML Resources

- [ ] https://www.youtube.com/results?search_query=python+pandas

- [ ] https://www.youtube.com/playlist?list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y

- [ ] https://www.youtube.com/playlist?list=PLyBBc46Y6aAz54aOUgKXXyTcEmpMisAq3

- [ ] http://gitready.com/

- [ ] https://hackernoon.com/git-in-2016-fad96ae22a15#.bv9lfuhu8

- [ ] 无量纲化

**Comment by zhenglaizhang** [comment]
## Math

* `mean`, `variance`, `standard deviation`: http://www.lifelaf.com/blog/?p=765
  
* `66.7%`, `95%`, `97%`

* 中位数、均方根、百分位数和四分差

* 中部单峰

* 当数据样本较小时，散点图是箱线图(boxplot)较好的替代方案。

**Comment by zhenglaizhang** [comment]
## Drawing

* https://en.wikipedia.org/wiki/Histogram
* 核密度估计(Kernel Density Estimates，简称KDE)
